name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Build React App
      run: |
        npm install --legacy-peer-deps
        
        # Inject the EC2 Backend URL dynamically during build
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env.production
        
        npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync Files to S3 Bucket
      run: |
        aws s3 sync build/ s3://${{ secrets.S3_BUCKET_FRONTEND }} --delete

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
          --paths "/*"
